name: invernova
description: A new Flutter project.
publish_to: none
version: 0.1.0
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.8
  the_apple_sign_in: ^1.1.1
  flutter_local_notifications: ^17.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  
flutter:
  uses-material-design: true
  assets:
    - assets/images/InverNovaLogo.jpg
    # - assets/images/google.png
    # - assets/images/apple.png
    - assets/images/InverNovaLogo.jpg
    # - assets/images/google.png