// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWVseUvz41t9SNMp1Ztl28W21Dyx5sXyg',
    appId: '1:379116688959:web:a59828de61174544694a8a',
    messagingSenderId: '379116688959',
    projectId: 'invernova-69060',
    authDomain: 'invernova-69060.firebaseapp.com',
    storageBucket: 'invernova-69060.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4X0fPlyrid-Hy31ri3rdzkZRG2TvbU-0',
    appId: '1:379116688959:android:b5ad9005464c65c5694a8a',
    messagingSenderId: '379116688959',
    projectId: 'invernova-69060',
    storageBucket: 'invernova-69060.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxh5gVGGtozVo_8LrXsimhB--4E0ITAw4',
    appId: '1:379116688959:ios:3f86cd078f623292694a8a',
    messagingSenderId: '379116688959',
    projectId: 'invernova-69060',
    storageBucket: 'invernova-69060.appspot.com',
    iosBundleId: 'com.example.invernova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxh5gVGGtozVo_8LrXsimhB--4E0ITAw4',
    appId: '1:379116688959:ios:be7c956141b259a6694a8a',
    messagingSenderId: '379116688959',
    projectId: 'invernova-69060',
    storageBucket: 'invernova-69060.appspot.com',
    iosBundleId: 'com.example.invernova.RunnerTests',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4X0fPlyrid-Hy31ri3rdzkZRG2TvbU-0',
    appId: '1:379116688959:windows:be7c956141b259a6694a8a',
    messagingSenderId: '379116688959',
    projectId: 'invernova-69060',
    storageBucket: 'invernova-69060.appspot.com',
  );
}
